replicaCount: 2

image:
  repository: 583931059504.dkr.ecr.eu-west-2.amazonaws.com/eks-2048
  tag: 8474986357767386bbb469613c83d11f64b9d39d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: eks.abdimajidcloud.com
  tls:
    enabled: true
    secretName: eks-2048-tls

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3