replicaCount: 3

image:
  repository: 583931059504.dkr.ecr.eu-west-2.amazonaws.com/eks-2048
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: eks.abdimajidcloud.com
  tls:
    enabled: true
    secretName: eks-2048-tls

resources: {}
