# PIPELINE 2 - APPLICATION CI

name: Application Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "helm/eks-2048/templates/**"
      - "helm/eks-2048/Chart.yaml"
      - ".github/workflows/application.yaml"

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: eu-west-2
  ECR_REGISTRY: 583931059504.dkr.ecr.eu-west-2.amazonaws.com
  ECR_REPOSITORY: eks-2048

jobs:
  application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan Terraform with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          soft_fail: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::583931059504:role/eks-project-github-actions-application
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            ./app

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Update image tag
        run: |
          sed -i "s|tag: .*|tag: ${{ github.sha }}|" helm/eks-2048/values.yaml

      - name: Push updated tag to Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add helm/eks-2048/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"

          git pull --rebase origin main
          git push origin main